- apps/api/src/index.ts
- pnpm-lock.yaml
@R1013-T  @waya279 
API側で必要なエンドポイントを書いてみました！認識違えばコメントください〜
```sh
.
├── guardian
├── sunshine
├── usage
├── apikey
  ├── auth
  └── generate
```
> feat: add routes

- README.md
- apps/api/.dev.vars.example
- apps/api/README.md
- apps/api/package.json
- apps/api/src/config/environment.ts
- apps/api/src/features/guardians/guardian.controller.ts
- apps/api/src/features/guardians/guardian.route.ts
- apps/api/src/features/guardians/guardian.service.ts
- apps/api/src/features/guardians/guardian.test.ts
- apps/api/src/features/guardians/guardian.usecase.ts
- apps/api/src/features/sunshines/sunshine.route.ts
- apps/api/src/index.ts
- apps/api/src/libs/openai.ts
- apps/api/test.sh
- apps/api/tsconfig.json
- packages/shared/package.json
- packages/shared/src/core/error.ts
- packages/shared/src/schemas/guardian.ts
- packages/shared/src/types/guardian.ts
- packages/shared/src/utils/error-handler.ts
- packages/shared/src/utils/result.ts
- packages/shared/tsconfig.json
- pnpm-lock.yaml
- https://github.com/TECH-C-LT/Peace-Net/issues/3
- https://github.com/TECH-C-LT/Peace-Net/issues/47
> Guardian APIの機能実装

- apps/api/src/features/guardians/guardian.service.ts
> fix: model name

- apps/api/helpers.sh
- apps/api/test.sh
WIPだけどテストケースを追加。
ディレクトリ適当なのでいい場所あれば。
> feat: test case

- apps/api/src/index.ts
- apps/api/test_powershell.ps1
> chore: add logger middleware

- apps/api/src/index.ts
> chore: add cors

- README.md
- apps/api/.dev.vars.example
- apps/api/package.json
- apps/api/src/config/environment.ts
- apps/api/src/libs/supabase.ts
- packages/shared/src/types/database.ts
- pnpm-lock.yaml
- supabase/migrations/20240806095114_remote_schema.sql
- supabase/migrations/20240806095504_add_api_management_tables.sql
- supabase/seed.sql
- Supabaseのクライアントライブラリが使いやすいので、ORM等は必要ないかも
- Deploy API / deploy (pull_request_target) は一旦無視でOK
> SupabaseクライアントをAPIに追加

- .github/workflows/api-deploy.yaml
> fix: workflow

- apps/api/wrangler.toml
https://github.com/TECH-C-LT/Peace-Net/actions/runs/10266395765/job/28404644616
CI落ちたの直すやつ
> fix: add main field

- apps/api/src/features/guardians/guardian.usecase.ts
- apps/api/src/features/guardians/guardian.utils.ts
> refactor: add checkFlagged and createCategories functions

- apps/api/src/index.ts
> chore: allow all origin

- apps/api/helpers.sh
- packages/shared/src/schemas/guardian.ts
related: #47 
defamation "誹謗中傷"フィールドを追加。
> fix: defamation field

- apps/web/package.json
- apps/web/src/app/layout.tsx
- pnpm-lock.yaml
> ✨ feat(web): analytics

- apps/api/src/features/sunshines/sunshine.route.ts
sunshine.routeファイルを追加しました。
POSTの実行確認済み
> feat: add sunshine.route

- apps/docs/docs/overview.md
- apps/docs/src/components/HomepageFeatures/index.tsx
related: #23
APIの概要とトップページの文言を追加
> docs: overview

- .github/workflows/docs-deploy.yaml
- apps/docs/package.json
- apps/docs/wrangler.toml
> workflow: deploy ci for docs

- apps/api/src/features/guardians/guardian.test.ts
- apps/api/src/features/sunshines/sunshine.controller.ts
- apps/api/src/features/sunshines/sunshine.route.ts
- apps/api/src/features/sunshines/sunshine.service.ts
- apps/api/src/features/sunshines/sunshine.usecase.ts
プロンプトは仮なので、時間があったら改善したいです。
`POST http://localhost:8787/v1/sunshines/text`
```json
{
"text": "失敗ばかりしてしまう"
}
```
```json
{
"text": "改善の機会をたくさん得ている"
}
```
> Sunshine Service の作成

- apps/web/src/app/components/footer-section.tsx
- apps/web/src/app/components/hero-section.tsx
- apps/web/src/components/navigation/index.tsx
- apps/web/src/lib/config.ts
- ドキュメントサイトのリンクを変更し共通化
- Githubのリンクを共通化
> Webのリンクを変更

- apps/api/wrangler.toml
- `wrangler.toml`で環境変数の管理が出来ます。
（シークレットはサイトやCLIから）
> APIのドキュメントリンクを変更

- apps/docs/docs/code-reference/sdk/golang.md
- apps/docs/sidebars.ts
sdkを作りました。
https://github.com/naruse666/peace-net-sdk-go
> docs: sdk go

- apps/web/src/app/components/beam.tsx
- apps/web/src/app/components/hero.tsx
- apps/web/src/app/components/scan-text.tsx
- apps/web/src/app/page.tsx
> 🌈 style(web): change web hero style

- package.json
see: https://pnpm.io/ja/only-allow-pnpm
> feat: enforce pnpm usage with preinstall script

- apps/web/src/app/(main)/dashboard/(palygroud)/components/playground-form.tsx
- apps/web/src/app/(main)/dashboard/(palygroud)/components/score-threshold-description.tsx
- https://github.com/TECH-C-LT/Peace-Net/issues/184
https://github.com/user-attachments/assets/2edc61ff-572b-47d1-8aa6-ecc421e98074
> playgroundで閾値がどの程度から判定するのか表示する

- apps/web/src/app/(main)/dashboard/(palygroud)/components/playground-form.tsx
- apps/web/src/app/(main)/dashboard/(palygroud)/components/score-threshold-description.tsx
- apps/web/src/app/(main)/dashboard/(palygroud)/schemas/index.ts
- packages/shared/src/schemas/guardian.ts
close: https://github.com/TECH-C-LT/Peace-Net/issues/190
> しきい値を`0-1`から`0.1-1`に変更

- apps/web/src/app/(main)/dashboard/(palygroud)/actions/guardian-image.ts
- apps/web/src/app/(main)/dashboard/(palygroud)/actions/guardian-text.ts
- apps/web/src/app/(main)/dashboard/(palygroud)/actions/index.ts
- apps/web/src/app/(main)/dashboard/(palygroud)/actions/sunshine.ts
- apps/web/src/app/(main)/dashboard/(palygroud)/components/form/guardian-image.tsx
- apps/web/src/app/(main)/dashboard/(palygroud)/components/form/guardian-text.tsx
- apps/web/src/app/(main)/dashboard/(palygroud)/components/form/sunshine.tsx
- apps/web/src/app/(main)/dashboard/(palygroud)/components/playground-form.tsx
- apps/web/src/app/(main)/dashboard/(palygroud)/components/result-syntax.tsx
- apps/web/src/app/(main)/dashboard/(palygroud)/components/submit-button.tsx
- apps/web/src/app/(main)/dashboard/(palygroud)/schemas/guardian.ts
- apps/web/src/app/(main)/dashboard/(palygroud)/schemas/index.ts
- apps/web/src/app/(main)/dashboard/(palygroud)/schemas/sunshine.ts
- **feat(web): split playground schemas**
- **feat(web): split playground actions**
- **feat(web): add submit button**
- **refactor(web): update result syntax**
- **feat(web): split playground forms**
> Guardian APIの画像のプレイグラウンド

- apps/web/src/app/(main)/dashboard/(palygroud)/components/limit-reached-dialog.tsx
closes: https://github.com/TECH-C-LT/Peace-Net/issues/183
> refactor: add document link to limit dialog

- apps/api/src/features/prisms/prism.controller.ts
- apps/api/src/features/prisms/prism.route.ts
- apps/api/src/features/prisms/prism.service.ts
- apps/api/src/features/prisms/prism.usecase.ts
- apps/api/src/features/usages/usage.facade.ts
- apps/api/src/index.ts
- packages/shared/src/schemas/prism.ts
- packages/shared/src/types/prism.ts
closes: https://github.com/TECH-C-LT/Peace-Net/issues/291
> [!NOTE]
> **POST**`http://localhost:8787/v1/prisms/text`
> ### Request
> ```json
> {
>    "text": "元気がいいね"
> }
> ```
> ### Response
> ```json
> {
>    "positive": "とても活気があるね" ,
>    "negative": "少し騒がしいかもしれないね"
> }
> PrismAPIの実装

- apps/api/src/features/guardians/guardian.route.ts
- apps/api/src/features/guardians/guardianImage.controller.ts
- apps/api/src/features/guardians/guardianText.controller.ts
- apps/api/src/libs/logger.ts
related: #196 
いい感じに出た
text
```sh
{ request: '<-- POST /v1/guardians/text' }
{
request: HonoRequest {
raw: Request {
method: 'POST',
url: 'http://api.pe-ace.net/v1/guardians/text',
headers: [Headers],
redirect: 'manual',
fetcher: [Fetcher],
signal: [AbortSignal],
cf: [Object],
integrity: '',
keepalive: false,
body: [ReadableStream],
bodyUsed: true
},
routeIndex: 4,
path: '/v1/guardians/text',
bodyCache: { json: [Promise] },
cachedBody: [Function: cachedBody]
},
id: 'd5b270cb-2e4f-4027-8ce5-08bf44dff3f6',
timestamp: '2024-10-11T10:52:07.700Z',
apiVersion: '1.6.2',
level: 'INFO',
model: 'gpt-4o-mini',
apiKind: 'guardian',
featureKind: 'text',
userId: undefined,
text: '東大医学部頭悪くないか？',
score_threshold: 0.5,
result: {
flagged: false,
categories: {
sexual: false,
hate: false,
self_harm: false, …
```
> chore: guardian log

- apps/api/src/features/sunshines/sunshine.controller.ts
- apps/api/src/features/sunshines/sunshine.route.ts
- apps/api/src/libs/logger.ts
close: #196 
いい感じ
```sh
{ request: '<-- POST /v1/sunshines/text' }
{
request: HonoRequest {
raw: Request {
method: 'POST',
url: 'http://api.pe-ace.net/v1/sunshines/text',
headers: [Headers],
redirect: 'manual',
fetcher: [Fetcher],
signal: [AbortSignal],
cf: [Object],
integrity: '',
keepalive: false,
body: [ReadableStream],
bodyUsed: true
},
routeIndex: 4,
path: '/v1/sunshines/text',
bodyCache: { json: [Promise] },
cachedBody: [Function: cachedBody]
},
id: '5f3a5647-c04f-4f1d-a339-48516881c145',
timestamp: '2024-10-11T12:04:47.267Z',
apiVersion: '1.6.2',
level: 'INFO',
model: 'gpt-4o-mini',
apiKind: 'sunshine',
userId: undefined,
text: '東大医学部頭悪くないか？',
result: { text: '東大医学部は非常に優秀な学生が集まる場所ですが、さらなる成長の余地があるかもしれませんね。' }
}
{ request: '--> POST /v1/sunshines/text \x1B[32m200\x1B[0m 1s' } …
```
> chore: sunshine log
